import { createCipheriv, createDecipheriv, randomBytes } from 'node:crypto';
import { pool, withTransaction } from '@platform/database';
import { uuidv7 } from '@platform/domain';
import { GoogleEmailProvider, MicrosoftEmailProvider, type EmailProvider } from '@platform/email';

const DATABASE_URL=process.env.DATABASE_URL; const KEY=process.env.MFA_ENCRYPTION_KEY;
if(!DATABASE_URL||!KEY) throw new Error('DATABASE_URL and MFA_ENCRYPTION_KEY are required');
function decrypt(value:string){const b=Buffer.from(value,'base64');const key=Buffer.from(KEY!,'base64');const d=createDecipheriv('aes-256-gcm',key,b.subarray(0,12));d.setAuthTag(b.subarray(12,28));return Buffer.concat([d.update(b.subarray(28)),d.final()]).toString();}
function provider(row:any):EmailProvider{return row.provider==='GOOGLE'?new GoogleEmailProvider(process.env.GOOGLE_CLIENT_ID!,process.env.GOOGLE_CLIENT_SECRET!):new MicrosoftEmailProvider(process.env.MICROSOFT_CLIENT_ID!,process.env.MICROSOFT_CLIENT_SECRET!,process.env.MICROSOFT_TENANT??'common');}
async function syncAccount(row:any){const p=provider(row);let access=decrypt(row.access_token_encrypted);let refresh=row.refresh_token_encrypted?decrypt(row.refresh_token_encrypted):undefined;if(row.token_expires_at&&new Date(row.token_expires_at).getTime()<Date.now()+60_000){if(!refresh)throw new Error('refresh token unavailable');const t=await p.refresh(refresh);access=t.accessToken;if(t.refreshToken)refresh=t.refreshToken;await withTransaction(row.tenant_id,tx=>tx.query('UPDATE email_accounts SET access_token_encrypted=$2,refresh_token_encrypted=COALESCE($3,refresh_token_encrypted),token_expires_at=$4,updated_at=NOW(),last_error=NULL WHERE id=$1',[row.id,encrypt(access),refresh?encrypt(refresh):null,t.expiresAt??null]));}
const synced=await p.syncMessages({accessToken:access, ...(refresh?{refreshToken:refresh}:{})},row.sync_cursor??undefined);
for(const m of synced.messages){const from=m.from?.toLowerCase();if(!from)continue;await withTransaction(row.tenant_id,async tx=>{let c=(await tx.query<{id:string}>('SELECT id FROM communication_contacts WHERE tenant_id=$1 AND lower(email)=lower($2)',[row.tenant_id,from])).rows[0];if(!c){c={id:uuidv7()};await tx.query('INSERT INTO communication_contacts(id,tenant_id,email) VALUES($1,$2,$3)',[c.id,row.tenant_id,from]);}const thread=m.threadId??m.rfcMessageId??m.id;let conv=(await tx.query<{id:string}>('SELECT id FROM conversations WHERE tenant_id=$1 AND contact_id=$2 AND channel=\'EMAIL\' AND thread_key=$3',[row.tenant_id,c.id,thread])).rows[0];if(!conv){conv={id:uuidv7()};await tx.query('INSERT INTO conversations(id,tenant_id,contact_id,channel,thread_key,subject,last_message_at) VALUES($1,$2,$3,\'EMAIL\',$4,$5,$6)',[conv.id,row.tenant_id,c.id,thread,m.subject??null,m.receivedAt??new Date()]);}const exists=await tx.query('SELECT 1 FROM messages WHERE tenant_id=$1 AND provider=$2 AND provider_message_id=$3',[row.tenant_id,row.provider.toLowerCase(),m.id]);if(exists.rowCount)return;const msgId=uuidv7();await tx.query(`INSERT INTO messages(id,tenant_id,conversation_id,direction,channel,sender,recipient,provider,provider_message_id,provider_thread_id,rfc_message_id,in_reply_to,status,body,occurred_at) VALUES($1,$2,$3,'INBOUND','EMAIL',$4,$5,$6,$7,$8,$9,$10,'RECEIVED',$11,$12)`,[msgId,row.tenant_id,conv.id,m.from,m.to[0]??row.email,row.provider.toLowerCase(),m.id,m.threadId??null,m.rfcMessageId??null,m.inReplyTo??null,m.text??m.html??'',m.receivedAt??new Date()]);await tx.query('UPDATE conversations SET last_message_at=$2,unread_count=unread_count+1,updated_at=NOW() WHERE id=$1',[conv.id,m.receivedAt??new Date()]);await tx.query(`INSERT INTO engagement_events(id,tenant_id,conversation_id,contact_id,event_type,subject_id,data,occurred_at) VALUES($1,$2,$3,$4,'email.received',$5,$6,$7) ON CONFLICT DO NOTHING`,[uuidv7(),row.tenant_id,conv.id,c.id,msgId,JSON.stringify({provider:row.provider}),m.receivedAt??new Date()]);await tx.query(`INSERT INTO communication_notifications(id,tenant_id,type,title,body,data) VALUES($1,$2,'email_reply','New email reply',$3,$4)`,[uuidv7(),row.tenant_id,`Email from ${m.from}`,m.subject??'',JSON.stringify({conversation_id:conv.id,message_id:msgId})]);});}
await withTransaction(row.tenant_id,tx=>tx.query('UPDATE email_accounts SET sync_cursor=$2,last_sync_at=NOW(),sync_status=\'ACTIVE\',last_error=NULL,updated_at=NOW() WHERE id=$1',[row.id,synced.nextCursor??row.sync_cursor??null]));}
function encrypt(value:string){const key=Buffer.from(KEY!,'base64');const iv=randomBytes(12);const cipher=createCipheriv('aes-256-gcm',key,iv);const text=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),text]).toString('base64');}

let running=true;process.on('SIGINT',()=>{running=false});process.on('SIGTERM',()=>{running=false});
console.log('email integration worker ready');
while(running){try{const accounts=(await pool.query(`SELECT * FROM email_accounts WHERE sync_status<>'DISCONNECTED' AND (last_sync_at IS NULL OR last_sync_at<NOW()-INTERVAL '15 seconds') ORDER BY last_sync_at NULLS FIRST LIMIT 10`)).rows;for(const row of accounts){try{await syncAccount(row);}catch(e){await withTransaction(row.tenant_id,tx=>tx.query('UPDATE email_accounts SET sync_status=\'ERROR\',last_error=$2,updated_at=NOW() WHERE id=$1',[row.id,e instanceof Error?e.message:'sync failed']));}}}catch(e){console.error(e);}await new Promise(r=>setTimeout(r,5000));}
await pool.end();