export type EmailProviderName = 'GOOGLE'|'MICROSOFT';
export interface EmailAccountTokens { accessToken: string; refreshToken?: string; expiresAt?: Date; }
export interface EmailMessage { id: string; threadId?: string; rfcMessageId?: string; from: string; to: string[]; subject?: string; text?: string; html?: string; receivedAt?: string; inReplyTo?: string; }
export interface EmailProvider { authorize(state: string, redirectUri: string): string; exchangeCode(code: string, redirectUri: string): Promise<EmailAccountTokens>; refresh(refreshToken: string): Promise<EmailAccountTokens>; send(tokens: EmailAccountTokens, input: {to:string[];subject:string;text?:string;html?:string;threadId?:string}): Promise<{providerMessageId:string;threadId?:string;rfcMessageId?:string}>; getMessage(tokens: EmailAccountTokens,id:string): Promise<EmailMessage>; syncMessages(tokens: EmailAccountTokens,cursor?:string): Promise<{messages:EmailMessage[];nextCursor?:string}>; }
function b64url(input:string|Uint8Array){return Buffer.from(input).toString('base64url');}
function googleBasic(subject:string,text:string,html?:string){const body=html?`Content-Type: text/html; charset=UTF-8\r\n\r\n${html}`:text; return b64url(`Subject: ${subject}\r\nMIME-Version: 1.0\r\nContent-Type: ${html?'text/html':'text/plain'}; charset=UTF-8\r\n\r\n${body}`);}
export class GoogleEmailProvider implements EmailProvider {
 constructor(private readonly clientId:string, private readonly clientSecret:string, private readonly authorizeEndpoint='https://accounts.google.com/o/oauth2/v2/auth', private readonly tokenEndpoint='https://oauth2.googleapis.com/token'){}
 authorize(state:string,redirectUri:string){const p=new URLSearchParams({client_id:this.clientId,redirect_uri:redirectUri,response_type:'code',access_type:'offline',prompt:'consent',scope:'openid email https://www.googleapis.com/auth/gmail.send https://www.googleapis.com/auth/gmail.readonly',state});return `${this.authorizeEndpoint}?${p}`;}
 async exchangeCode(code:string,redirectUri:string){return this.token({code,redirect_uri:redirectUri,grant_type:'authorization_code'});}
 async refresh(refreshToken:string){return this.token({refresh_token:refreshToken,grant_type:'refresh_token'});}
 private async token(body:Record<string,string>){const r=await fetch(this.tokenEndpoint,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({...body,client_id:this.clientId,client_secret:this.clientSecret})}); if(!r.ok) throw new Error(`Google token exchange failed: ${r.status}`); const j=await r.json() as any; return {accessToken:j.access_token, ...(j.refresh_token?{refreshToken:j.refresh_token}:{}), ...(j.expires_in?{expiresAt:new Date(Date.now()+j.expires_in*1000)}:{})};}
 private headers(t:EmailAccountTokens){return {authorization:`Bearer ${t.accessToken}`,'content-type':'application/json'};}
 async send(t: EmailAccountTokens,input: {to:string[];subject:string;text?:string;html?:string;threadId?:string}){const raw=googleBasic(input.subject,input.text??'',input.html); const r=await fetch('https://gmail.googleapis.com/gmail/v1/users/me/messages/send',{method:'POST',headers:this.headers(t),body:JSON.stringify({raw, ...(input.threadId?{threadId:input.threadId}:{})})}); if(!r.ok) throw new Error(`Gmail send failed: ${r.status}`); const j=await r.json() as any; return {providerMessageId:j.id,threadId:j.threadId};}
 async getMessage(t: EmailAccountTokens,id:string): Promise<EmailMessage>{const r=await fetch(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${encodeURIComponent(id)}?format=full`,{headers:this.headers(t)});if(!r.ok)throw new Error(`Gmail get failed: ${r.status}`);const j=await r.json() as any;const headers=Object.fromEntries((j.payload?.headers??[]).map((h:any)=>[String(h.name).toLowerCase(),String(h.value)]));const decode=(v?:string)=>v?Buffer.from(v,'base64url').toString('utf8'):'';const parts=(j.payload?.parts??[]);const textPart=parts.find((x:any)=>x.mimeType==='text/plain')?.body?.data;const htmlPart=parts.find((x:any)=>x.mimeType==='text/html')?.body?.data;return {id:j.id,threadId:j.threadId,from:headers.from??'',to:(headers.to??'').split(',').map((x:string)=>x.trim()).filter(Boolean),subject:headers.subject??'',...(headers['message-id']?{rfcMessageId:headers['message-id']}:{ }),...(headers['in-reply-to']?{inReplyTo:headers['in-reply-to']}:{ }),...(textPart?{text:decode(textPart)}:{}),...(htmlPart?{html:decode(htmlPart)}:{ }),...(j.internalDate?{receivedAt:new Date(Number(j.internalDate)).toISOString()}:{})};}
 async syncMessages(t: EmailAccountTokens,cursor?:string){let url='https://gmail.googleapis.com/gmail/v1/users/me/history?historyTypes=messageAdded&maxResults=100'; if(cursor)url+=`&startHistoryId=${encodeURIComponent(cursor)}`; const r=await fetch(url,{headers:this.headers(t)});if(!r.ok){if(r.status===404) return {messages:[],nextCursor:undefined};throw new Error(`Gmail sync failed: ${r.status}`);}const j=await r.json() as any; const ids=(j.history??[]).flatMap((h:any)=>h.messagesAdded??[]).map((x:any)=>x.message?.id).filter(Boolean); const messages=[] as EmailMessage[]; for(const id of ids)messages.push(await this.getMessage(t,id)); return {messages,nextCursor:j.historyId};}
}
export class MicrosoftEmailProvider implements EmailProvider {
 constructor(private readonly clientId:string, private readonly clientSecret:string, private readonly tenant='common'){}
 private endpoint(){return `https://login.microsoftonline.com/${this.tenant}/oauth2/v2.0`}
 authorize(state:string,redirectUri:string){const p=new URLSearchParams({client_id:this.clientId,response_type:'code',redirect_uri:redirectUri,response_mode:'query',scope:'offline_access openid profile email Mail.Read Mail.Send',state});return `${this.endpoint()}/authorize?${p}`;}
 async exchangeCode(code:string,redirectUri:string){return this.token({code,redirect_uri:redirectUri,grant_type:'authorization_code'});}
 async refresh(refreshToken:string){return this.token({refresh_token:refreshToken,grant_type:'refresh_token'});}
 private async token(body:Record<string,string>){const r=await fetch(`${this.endpoint()}/token`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({...body,client_id:this.clientId,client_secret:this.clientSecret})});if(!r.ok)throw new Error(`Microsoft token exchange failed: ${r.status}`);const j=await r.json() as any;return {accessToken:j.access_token,...(j.refresh_token?{refreshToken:j.refresh_token}:{}),...(j.expires_in?{expiresAt:new Date(Date.now()+j.expires_in*1000)}:{})};}
 private headers(t:EmailAccountTokens){return {authorization:`Bearer ${t.accessToken}`,'content-type':'application/json'};}
 async send(t: EmailAccountTokens,input: {to:string[];subject:string;text?:string;html?:string;threadId?:string}){const r=await fetch('https://graph.microsoft.com/v1.0/me/sendMail',{method:'POST',headers:this.headers(t),body:JSON.stringify({message:{subject:input.subject,body:{contentType:input.html?'HTML':'Text',content:input.html??input.text??''},toRecipients:input.to.map((address:string)=>({emailAddress:{address}}))}})});if(!r.ok)throw new Error(`Microsoft send failed: ${r.status}`);return {providerMessageId:`sent-${Date.now()}`};}
 async getMessage(t: EmailAccountTokens,id:string): Promise<EmailMessage>{const r=await fetch(`https://graph.microsoft.com/v1.0/me/messages/${encodeURIComponent(id)}` ,{headers:this.headers(t)});if(!r.ok)throw new Error(`Microsoft get failed: ${r.status}`);const j=await r.json() as any;return {id:j.id,threadId:j.conversationId,rfcMessageId:j.internetMessageId,from:j.from?.emailAddress?.address??'',to:(j.toRecipients??[]).map((x:any)=>x.emailAddress?.address).filter(Boolean),subject:j.subject,text:j.body?.content,receivedAt:j.receivedDateTime,inReplyTo:j.internetMessageHeaders?.find((x:any)=>x.name.toLowerCase()==='in-reply-to')?.value};}
 async syncMessages(t: EmailAccountTokens,cursor?:string){const url=cursor??'https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messages/delta?$select=id,conversationId,internetMessageId,from,toRecipients,subject,body,receivedDateTime';const r=await fetch(url,{headers:this.headers(t)});if(!r.ok)throw new Error(`Microsoft sync failed: ${r.status}`);const j=await r.json() as any;const messages=[] as EmailMessage[];for(const item of j.value??[]){if(item['@removed'])continue;messages.push({id:item.id,threadId:item.conversationId,rfcMessageId:item.internetMessageId,from:item.from?.emailAddress?.address??'',to:(item.toRecipients??[]).map((x:any)=>x.emailAddress?.address).filter(Boolean),subject:item.subject,text:item.body?.content,receivedAt:item.receivedDateTime});}return {messages,nextCursor:j['@odata.nextLink']??j['@odata.deltaLink']};}
}